[runtime]
username = "chillguy" # in game username
uuid = "00000000-0000-0000-0000-000000000000"
accesstoken = "0"
usertype = "mojang"

[java]
max_memory = "4G" # allocated memory/ram/heap size (Xmx) structured like "2G" meaning 2 gigabytes

[installer]
version = "1.21.1"

[launcher]
update = "prompt" # updater  // valid values include "true" "prompt" "false"
